/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Vipul Rajput
 */
public class exercise extends javax.swing.JFrame {

    /**
     * Creates new form exercise
     */
    public exercise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chest = new javax.swing.JButton();
        biceps = new javax.swing.JButton();
        triceps = new javax.swing.JButton();
        shoulder = new javax.swing.JButton();
        back = new javax.swing.JButton();
        legs = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        abs = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menushow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        chest.setBackground(new java.awt.Color(255, 153, 0));
        chest.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        chest.setForeground(new java.awt.Color(255, 0, 0));
        chest.setText("CHEST");
        chest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        chest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chestMouseExited(evt);
            }
        });
        chest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chestActionPerformed(evt);
            }
        });
        jPanel1.add(chest);
        chest.setBounds(300, 200, 150, 60);

        biceps.setBackground(new java.awt.Color(255, 153, 0));
        biceps.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        biceps.setForeground(new java.awt.Color(255, 0, 0));
        biceps.setText("BICEPS");
        biceps.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        biceps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        biceps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bicepsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bicepsMouseExited(evt);
            }
        });
        biceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicepsActionPerformed(evt);
            }
        });
        jPanel1.add(biceps);
        biceps.setBounds(0, 200, 150, 60);

        triceps.setBackground(new java.awt.Color(255, 153, 0));
        triceps.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        triceps.setForeground(new java.awt.Color(255, 0, 0));
        triceps.setText("TRICEPS");
        triceps.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        triceps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triceps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tricepsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tricepsMouseExited(evt);
            }
        });
        triceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tricepsActionPerformed(evt);
            }
        });
        jPanel1.add(triceps);
        triceps.setBounds(150, 200, 150, 60);

        shoulder.setBackground(new java.awt.Color(255, 153, 0));
        shoulder.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        shoulder.setForeground(new java.awt.Color(255, 0, 0));
        shoulder.setText("SHOULDER");
        shoulder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        shoulder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shoulder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shoulderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shoulderMouseExited(evt);
            }
        });
        shoulder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoulderActionPerformed(evt);
            }
        });
        jPanel1.add(shoulder);
        shoulder.setBounds(450, 200, 150, 60);

        back.setBackground(new java.awt.Color(255, 153, 0));
        back.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(600, 200, 140, 60);

        legs.setBackground(new java.awt.Color(255, 153, 0));
        legs.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        legs.setForeground(new java.awt.Color(255, 0, 0));
        legs.setText("LEGS");
        legs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        legs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        legs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                legsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                legsMouseExited(evt);
            }
        });
        legs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legsActionPerformed(evt);
            }
        });
        jPanel1.add(legs);
        legs.setBounds(880, 200, 140, 60);

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 240, 190);

        abs.setBackground(new java.awt.Color(255, 153, 0));
        abs.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        abs.setForeground(new java.awt.Color(255, 0, 0));
        abs.setText("ABS");
        abs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        abs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                absMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                absMouseExited(evt);
            }
        });
        abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absActionPerformed(evt);
            }
        });
        jPanel1.add(abs);
        abs.setBounds(740, 200, 140, 60);

        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(900, 0, 40, 40);

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(970, 0, 40, 40);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/image/nextstep.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 194);

        menushow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/image/menu.jpg"))); // NOI18N
        jPanel1.add(menushow);
        menushow.setBounds(70, 270, 910, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chestMouseEntered
        chest.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m3.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_chestMouseEntered

    private void chestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chestMouseExited
        chest.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_chestMouseExited

    private void chestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestActionPerformed

    }//GEN-LAST:event_chestActionPerformed

    private void bicepsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bicepsMouseEntered

        biceps.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m1.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_bicepsMouseEntered

    private void bicepsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bicepsMouseExited
        biceps.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_bicepsMouseExited

    private void bicepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicepsActionPerformed

    }//GEN-LAST:event_bicepsActionPerformed

    private void tricepsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tricepsMouseEntered
        triceps.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m2.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_tricepsMouseEntered

    private void tricepsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tricepsMouseExited
        triceps.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_tricepsMouseExited

    private void tricepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tricepsActionPerformed
        
    }//GEN-LAST:event_tricepsActionPerformed

    private void shoulderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoulderMouseEntered
        shoulder.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m4.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_shoulderMouseEntered

    private void shoulderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoulderMouseExited
        shoulder.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_shoulderMouseExited

    private void shoulderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoulderActionPerformed
        
    }//GEN-LAST:event_shoulderActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
         back.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m5.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
    }//GEN-LAST:event_backActionPerformed

    private void legsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_legsMouseEntered
        legs.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m7.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_legsMouseEntered

    private void legsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_legsMouseExited
        legs.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_legsMouseExited

    private void legsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legsActionPerformed
      
    }//GEN-LAST:event_legsActionPerformed

    private void absMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absMouseEntered
        abs.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/m6.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_absMouseEntered

    private void absMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absMouseExited
        abs.setBackground(new Color(255,153,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/gym/image/menu.jpg"));
        menushow.setIcon(ii);
    }//GEN-LAST:event_absMouseExited

    private void absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absActionPerformed
        
    }//GEN-LAST:event_absActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(startgym.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
new startgym().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exercise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abs;
    private javax.swing.JButton back;
    private javax.swing.JButton biceps;
    private javax.swing.JButton chest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton legs;
    private javax.swing.JLabel menushow;
    private javax.swing.JButton shoulder;
    private javax.swing.JButton triceps;
    // End of variables declaration//GEN-END:variables
}
